#!/bin/bash
# run-codegen-validator-tests.sh — validate the canonical agent-generated outputs.
#
# Phase 3 deleted codegen-fresh.sh and codegen-sidebyside.sh; codegen now lives
# in the integrator agent's prose. This test suite cannot drive the agent from
# bash, so it instead pre-populates synthetic projects with the *expected* agent
# output (a reference impl that mirrors integrator.md Step 5 verbatim) and runs
# the unchanged validator over them. If a documented template is invalid, this
# test catches it.
#
# Coverage:
#   1. fresh / interstitial / no namespace          → PASS
#   2. fresh / rewarded / namespace MyGame.Services → PASS  (validates wrap + reward callback)
#   3. fresh / privacy AFTER init                   → FAIL  (negative golden)
#   4. side-by-side / firebase binding              → PASS  (validates 4 adapter files + 5th binding)
#   5. side-by-side / none binding                  → PASS  (validates TODO-stub variant)
#   6. side-by-side / Metica-prefixed names         → PASS  (validates collision-prefix path)

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VALIDATE="$PLUGIN_DIR/scripts/validate-integration.sh"
TEMPLATE_DIR="$PLUGIN_DIR/scripts/templates/sidebyside"

pass=0
fail=0

status_of() {
    printf '%s\n' "$1" | awk '
        /"status":[[:space:]]*"/ {
            n=index($0, "\"status\":")
            s=substr($0, n+9); sub(/^[^"]*"/, "", s); sub(/".*$/, "", s)
            print s; exit
        }'
}

make_fresh_project() {
    local dir; dir="$(mktemp -d -t metica-fresh-XXXXXX)"
    mkdir -p "$dir/Assets/Scripts" "$dir/ProjectSettings"
    printf 'm_EditorVersion: 2022.3.62f2\n' > "$dir/ProjectSettings/ProjectVersion.txt"
    echo "$dir"
}

make_sbs_project() {
    local dir; dir="$(mktemp -d -t metica-sbs-XXXXXX)"
    mkdir -p "$dir/Assets/MaxSdk/AppLovin/Editor" "$dir/Assets/Scripts" "$dir/ProjectSettings"
    printf 'm_EditorVersion: 2022.3.62f2\n' > "$dir/ProjectSettings/ProjectVersion.txt"
    printf '<?xml version="1.0"?><dependencies/>\n' > "$dir/Assets/MaxSdk/AppLovin/Editor/Dependencies.xml"
    cat > "$dir/Assets/Scripts/GameAd.cs" <<'EOF'
public class GameAd { void Init() { MaxSdk.Initialize(); } }
EOF
    echo "$dir"
}

# Reference impl of the agent's fresh-mode template (integrator.md Step 5).
# Args: project, namespace_or_empty, formats (csv), api_key, app_id
emit_fresh_bootstrap() {
    local project="$1" ns="$2" formats="$3" api="$4" app="$5"
    local out="$project/Assets/Scripts/MeticaBootstrap.cs"
    mkdir -p "$(dirname "$out")"

    local has_banner=0 has_inter=0 has_rew=0
    case ",$formats," in *,banner,*) has_banner=1 ;; esac
    case ",$formats," in *,interstitial,*) has_inter=1 ;; esac
    case ",$formats," in *,rewarded,*) has_rew=1 ;; esac

    {
        echo 'using UnityEngine;'
        echo 'using Metica;'
        echo 'using Metica.Ads;'
        echo ''
        echo '// Generated by metica-sdk-agents (fresh-mode codegen).'
        if [ -n "$ns" ]; then echo "namespace $ns {"; fi
        echo 'public class MeticaBootstrap : MonoBehaviour'
        echo '{'
        echo '    void Start()'
        echo '    {'
        if [ "$has_banner" = 1 ]; then
            echo '        MeticaAdsCallbacks.Banner.OnAdLoadSuccess += ad => Debug.Log("[Metica] banner loaded");'
            echo '        MeticaAdsCallbacks.Banner.OnAdLoadFailed += err => Debug.LogWarning("[Metica] banner failed");'
            echo '        MeticaAdsCallbacks.Banner.OnAdRevenuePaid += ad => Debug.Log("[Metica] banner revenue");'
        fi
        if [ "$has_inter" = 1 ]; then
            echo '        MeticaAdsCallbacks.Interstitial.OnAdLoadSuccess += ad => Debug.Log("[Metica] interstitial loaded");'
            echo '        MeticaAdsCallbacks.Interstitial.OnAdLoadFailed += err => Debug.LogWarning("[Metica] interstitial failed");'
            echo '        MeticaAdsCallbacks.Interstitial.OnAdShowSuccess += ad => Debug.Log("[Metica] interstitial shown");'
            echo '        MeticaAdsCallbacks.Interstitial.OnAdHidden += ad => Debug.Log("[Metica] interstitial hidden");'
            echo '        MeticaAdsCallbacks.Interstitial.OnAdRevenuePaid += ad => Debug.Log("[Metica] interstitial revenue");'
        fi
        if [ "$has_rew" = 1 ]; then
            echo '        MeticaAdsCallbacks.Rewarded.OnAdLoadSuccess += ad => Debug.Log("[Metica] rewarded loaded");'
            echo '        MeticaAdsCallbacks.Rewarded.OnAdLoadFailed += err => Debug.LogWarning("[Metica] rewarded failed");'
            echo '        MeticaAdsCallbacks.Rewarded.OnAdShowSuccess += ad => Debug.Log("[Metica] rewarded shown");'
            echo '        MeticaAdsCallbacks.Rewarded.OnAdHidden += ad => Debug.Log("[Metica] rewarded hidden");'
            echo '        MeticaAdsCallbacks.Rewarded.OnAdRewarded += ad => Debug.Log("[Metica] rewarded reward granted");'
            echo '        MeticaAdsCallbacks.Rewarded.OnAdRevenuePaid += ad => Debug.Log("[Metica] rewarded revenue");'
        fi
        echo '        MeticaSdk.Ads.SetHasUserConsent(true);'
        echo '        MeticaSdk.Ads.SetDoNotSell(false);'
        printf '        var config = new MeticaInitConfig("%s", "%s", null);\n' "$api" "$app"
        echo '        MeticaSdk.Initialize(config, null, response => { Debug.Log("[Metica] SDK initialized"); });'
        if [ "$has_banner" = 1 ]; then
            echo '        MeticaSdk.Ads.CreateBanner("banner_main", new MeticaAdViewConfiguration(MeticaAdViewPosition.BottomCenter));'
            echo '        MeticaSdk.Ads.LoadBanner("banner_main");'
            echo '        MeticaSdk.Ads.ShowBanner("banner_main");'
        fi
        [ "$has_inter" = 1 ] && echo '        MeticaSdk.Ads.LoadInterstitial("interstitial_main");'
        [ "$has_rew" = 1 ] && echo '        MeticaSdk.Ads.LoadRewarded("rewarded_main");'
        echo '    }'
        if [ "$has_inter" = 1 ]; then
            echo ''
            echo '    public void ShowInterstitial() {'
            echo '        if (MeticaSdk.Ads.IsInterstitialReady("interstitial_main"))'
            echo '            MeticaSdk.Ads.ShowInterstitial("interstitial_main");'
            echo '    }'
        fi
        if [ "$has_rew" = 1 ]; then
            echo ''
            echo '    public void ShowRewarded() {'
            echo '        if (MeticaSdk.Ads.IsRewardedReady("rewarded_main"))'
            echo '            MeticaSdk.Ads.ShowRewarded("rewarded_main");'
            echo '    }'
        fi
        echo '}'
        if [ -n "$ns" ]; then echo '}'; fi
    } > "$out"
}

# Reference impl of the agent's side-by-side codegen.
# Reads templates verbatim and applies the documented transforms.
# Args: project, namespace, prefix (may be empty), api_key, app_id, max_key
emit_sbs_files() {
    local project="$1" ns="$2" prefix="$3" api="$4" app="$5" maxk="$6"
    local out_dir="$project/Assets/Scripts/Metica"
    mkdir -p "$out_dir"

    local files=(IAdService MaxAdService MeticaAdService AdServiceRouter)
    for stem in "${files[@]}"; do
        local tmpl="$TEMPLATE_DIR/$stem.cs.tmpl"
        local out="$out_dir/${prefix}${stem}.cs"
        # Apply transforms via sed: namespace + identifier prefix + key substitution.
        sed \
            -e "s|namespace Metica\\.AbTest|namespace $ns|g" \
            -e "s|} // namespace Metica\\.AbTest|} // namespace $ns|g" \
            -e "s|__METICA_API_KEY__|$api|g" \
            -e "s|__METICA_APP_ID__|$app|g" \
            -e "s|__MAX_SDK_KEY__|$maxk|g" \
            "$tmpl" > "$out"
        if [ -n "$prefix" ]; then
            # Replace identifier references in this order (no word-boundary regex,
            # which BSD sed lacks). Order matters: rename the original class names
            # FIRST so later renames don't accidentally match inside earlier
            # prefixed forms (e.g. MeticaAdService → MeticaMeticaAdService must
            # happen before AdServiceRouter → MeticaAdServiceRouter, otherwise
            # MeticaAdServiceRouter would re-match as a prefix and become
            # MeticaMeticaAdServiceRouter).
            sed -i.bak \
                -e "s|MeticaAdService|${prefix}MeticaAdService|g" \
                -e "s|MaxAdService|${prefix}MaxAdService|g" \
                -e "s|IAdService|${prefix}IAdService|g" \
                -e "s|AdServiceRouter|${prefix}AdServiceRouter|g" \
                "$out"
            rm -f "$out.bak"
            # Adjust the output filename: emit_sbs_files already wrote to ${prefix}${stem}.cs
            # so no rename needed.
        fi
    done
}

# Args: project, namespace, prefix, variant (firebase|none), key
emit_rollout_binding() {
    local project="$1" ns="$2" prefix="$3" variant="$4" key="$5"
    local out="$project/Assets/Scripts/Metica/${prefix}MeticaRolloutBinding.cs"
    local router="${prefix}AdServiceRouter"

    case "$variant" in
        firebase)
            cat > "$out" <<EOF
using Firebase.RemoteConfig;
using UnityEngine;

namespace $ns
{
    static class MeticaRolloutBinding
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Bind()
        {
            $router.RolloutDecisionFunc = () =>
                FirebaseRemoteConfig.DefaultInstance.GetValue("$key").BooleanValue;
        }
    }
}
EOF
            ;;
        none)
            cat > "$out" <<EOF
using UnityEngine;

namespace $ns
{
    static class MeticaRolloutBinding
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Bind()
        {
            // CHOOSE ONE AND UNCOMMENT — DO NOT SHIP THIS STUB
            //
            // Firebase Remote Config:
            // $router.RolloutDecisionFunc = () =>
            //     Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.GetValue("$key").BooleanValue;
            //
            // AppMetrica:
            // $router.RolloutDecisionFunc = () =>
            //     Io.AppMetrica.AppMetrica.GetFeatureFlag("$key");
            //
            // Unity Remote Config:
            // $router.RolloutDecisionFunc = () =>
            //     Unity.Services.RemoteConfig.RemoteConfigService.Instance.appConfig.GetBool("$key");
        }
    }
}
EOF
            ;;
    esac
}

run_case() {
    local name="$1" expected="$2" project="$3" mode="$4"
    local json status
    json="$(bash "$VALIDATE" --project="$project" --mode="$mode" 2>&1 || true)"
    status="$(status_of "$json")"
    if [ "$status" = "$expected" ]; then
        echo "  PASS  $name"
        pass=$((pass+1))
    else
        echo "  FAIL  $name  (expected $expected, got $status)"
        echo "$json" | head -40 | sed 's/^/        /'
        fail=$((fail+1))
    fi
    rm -rf "$project"
}

echo "=== run-codegen-validator-tests.sh ==="

# 1. fresh / interstitial / no namespace
p="$(make_fresh_project)"
emit_fresh_bootstrap "$p" "" "interstitial" "ABC123" "XYZ987"
run_case "fresh interstitial no-ns" "PASS" "$p" "fresh"

# 2. fresh / rewarded / namespace MyGame.Services
p="$(make_fresh_project)"
emit_fresh_bootstrap "$p" "MyGame.Services" "interstitial,rewarded" "ABC123" "XYZ987"
# also assert the namespace and reward callback are present
if grep -q "namespace MyGame.Services" "$p/Assets/Scripts/MeticaBootstrap.cs" \
    && grep -q "Rewarded.OnAdRewarded" "$p/Assets/Scripts/MeticaBootstrap.cs"; then
    run_case "fresh rewarded ns=MyGame.Services" "PASS" "$p" "fresh"
else
    echo "  FAIL  fresh rewarded ns=MyGame.Services  (template missing expected lines)"
    fail=$((fail+1))
    rm -rf "$p"
fi

# 3. fresh / privacy AFTER init → validator FAIL (negative golden)
p="$(make_fresh_project)"
emit_fresh_bootstrap "$p" "" "interstitial" "ABC123" "XYZ987"
# Swap order: move SetHasUserConsent/SetDoNotSell to AFTER MeticaSdk.Initialize.
awk '
    /MeticaSdk.Ads.SetHasUserConsent\(true\);/ { consent=$0; next }
    /MeticaSdk.Ads.SetDoNotSell\(false\);/      { dns=$0; next }
    /MeticaSdk.Initialize\(/ {
        print
        print "        " consent
        print "        " dns
        next
    }
    { print }
' "$p/Assets/Scripts/MeticaBootstrap.cs" > "$p/Assets/Scripts/MeticaBootstrap.cs.new"
mv "$p/Assets/Scripts/MeticaBootstrap.cs.new" "$p/Assets/Scripts/MeticaBootstrap.cs"
run_case "fresh privacy-after-init (negative)" "FAIL" "$p" "fresh"

# 4. side-by-side / firebase binding
p="$(make_sbs_project)"
emit_sbs_files "$p" "Metica.AbTest" "" "ABC123" "XYZ987" "MAXKEY99"
emit_rollout_binding "$p" "Metica.AbTest" "" "firebase" "metica_rollout"
if grep -q "FirebaseRemoteConfig.DefaultInstance.GetValue" "$p/Assets/Scripts/Metica/MeticaRolloutBinding.cs"; then
    run_case "sbs firebase binding" "PASS" "$p" "side-by-side"
else
    echo "  FAIL  sbs firebase binding  (binding template missing FirebaseRemoteConfig call)"
    fail=$((fail+1))
    rm -rf "$p"
fi

# 5. side-by-side / none binding (TODO-stub)
p="$(make_sbs_project)"
emit_sbs_files "$p" "Metica.AbTest" "" "ABC123" "XYZ987" "MAXKEY99"
emit_rollout_binding "$p" "Metica.AbTest" "" "none" "metica_rollout"
all_three=1
grep -q "Firebase Remote Config:"     "$p/Assets/Scripts/Metica/MeticaRolloutBinding.cs" || all_three=0
grep -q "AppMetrica:"                  "$p/Assets/Scripts/Metica/MeticaRolloutBinding.cs" || all_three=0
grep -q "Unity Remote Config:"         "$p/Assets/Scripts/Metica/MeticaRolloutBinding.cs" || all_three=0
if [ "$all_three" = 1 ]; then
    run_case "sbs none binding (TODO stub)" "PASS" "$p" "side-by-side"
else
    echo "  FAIL  sbs none binding (TODO stub)  (missing one of the three commented examples)"
    fail=$((fail+1))
    rm -rf "$p"
fi

# 6. side-by-side / Metica-prefixed names (collision-prefix path)
p="$(make_sbs_project)"
# Pre-existing IAdService in the project triggers prefix mode.
mkdir -p "$p/Assets/Scripts/Existing"
cat > "$p/Assets/Scripts/Existing/IAdService.cs" <<'EOF'
namespace Existing { public interface IAdService { } }
EOF
emit_sbs_files "$p" "MyGame.Services.Metica" "Metica" "ABC123" "XYZ987" "MAXKEY99"
emit_rollout_binding "$p" "MyGame.Services.Metica" "Metica" "firebase" "metica_rollout"
if grep -q "MeticaAdServiceRouter" "$p/Assets/Scripts/Metica/MeticaAdServiceRouter.cs" \
    && grep -q "namespace MyGame.Services.Metica" "$p/Assets/Scripts/Metica/MeticaAdServiceRouter.cs"; then
    run_case "sbs Metica-prefixed names" "PASS" "$p" "side-by-side"
else
    echo "  FAIL  sbs Metica-prefixed names  (prefix or namespace not applied)"
    fail=$((fail+1))
    rm -rf "$p"
fi

echo
echo "Pass: $pass   Fail: $fail"
[ "$fail" = "0" ] || exit 1
