#!/bin/bash
# codegen-fresh.sh — generate a MeticaBootstrap.cs for a fresh-mode integration.
# Produces a single C# file that the validator approves: privacy precedes init,
# init called exactly once, per-format callbacks subscribed, load/show parity.
#
# Usage:
#   codegen-fresh.sh --project=<path> [--api-key=KEY] [--app-id=ID]
#                    [--formats=banner,interstitial,rewarded] [--force]
# Exit: 0 on success.

set -u
set -o pipefail

PROJECT=""
API_KEY="YOUR_METICA_API_KEY"
APP_ID="YOUR_METICA_APP_ID"
FORMATS="interstitial"
FORCE=0

for arg in "$@"; do
    case $arg in
        --project=*)  PROJECT="${arg#*=}" ;;
        --api-key=*)  API_KEY="${arg#*=}" ;;
        --app-id=*)   APP_ID="${arg#*=}" ;;
        --formats=*)  FORMATS="${arg#*=}" ;;
        --force)      FORCE=1 ;;
        -h|--help)
            sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "Unknown arg: $arg" >&2; exit 1 ;;
    esac
done

[ -n "$PROJECT" ]        || { echo "Missing --project" >&2; exit 1; }
[ -d "$PROJECT" ]        || { echo "Project not found: $PROJECT" >&2; exit 1; }
[ -d "$PROJECT/Assets" ] || { echo "Not a Unity project (no Assets/): $PROJECT" >&2; exit 1; }
[ -n "$FORMATS" ]        || { echo "Empty --formats" >&2; exit 1; }

# Validate formats. Trim whitespace from each token.
IFS=',' read -ra FORMAT_LIST <<< "$FORMATS"
NORMALIZED=""
for fmt in "${FORMAT_LIST[@]}"; do
    fmt="${fmt#"${fmt%%[![:space:]]*}"}"   # ltrim
    fmt="${fmt%"${fmt##*[![:space:]]}"}"   # rtrim
    case "$fmt" in
        banner|interstitial|rewarded) NORMALIZED="${NORMALIZED:+$NORMALIZED,}$fmt" ;;
        "") echo "Empty format name" >&2; exit 1 ;;
        *) echo "Unknown format: $fmt (allowed: banner, interstitial, rewarded)" >&2; exit 1 ;;
    esac
done
FORMATS="$NORMALIZED"

# Reject empty / control-char-bearing API key & App ID
cs_escape() {
    local s="$1"
    case "$s" in
        *$'\n'*|*$'\r'*|*$'\t'*) echo "ERROR: API key / App ID must not contain newlines or tabs." >&2; exit 1 ;;
    esac
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '%s' "$s"
}
[ -n "$API_KEY" ] || { echo "Empty --api-key" >&2; exit 1; }
[ -n "$APP_ID" ]  || { echo "Empty --app-id" >&2; exit 1; }
# command substitution runs cs_escape in a subshell — its `exit 1` only
# escapes the subshell, so we must propagate the non-zero status here.
API_KEY_SAFE=$(cs_escape "$API_KEY") || exit 1
APP_ID_SAFE=$(cs_escape "$APP_ID")   || exit 1

has_format() {
    case ",$FORMATS," in
        *",$1,"*) return 0 ;;
        *) return 1 ;;
    esac
}

OUT_DIR="$PROJECT/Assets/Scripts"
OUT_FILE="$OUT_DIR/MeticaBootstrap.cs"

if [ -f "$OUT_FILE" ] && [ "$FORCE" != "1" ]; then
    echo "ERROR: $OUT_FILE already exists. Pass --force to overwrite." >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# --- Emit the C# file ---

{
    cat <<'HEADER'
using UnityEngine;
using Metica;
using Metica.Ads;

// Generated by metica-sdk-agents (fresh-mode codegen).
public class MeticaBootstrap : MonoBehaviour
{
    void Start()
    {
HEADER

    if has_format banner; then
        cat <<'BANNER_CB'
        MeticaAdsCallbacks.Banner.OnAdLoadSuccess += ad => Debug.Log("[Metica] banner loaded");
        MeticaAdsCallbacks.Banner.OnAdLoadFailed += err => Debug.LogWarning("[Metica] banner failed");
        MeticaAdsCallbacks.Banner.OnAdRevenuePaid += ad => Debug.Log("[Metica] banner revenue");

BANNER_CB
    fi

    if has_format interstitial; then
        cat <<'INTER_CB'
        MeticaAdsCallbacks.Interstitial.OnAdLoadSuccess += ad => Debug.Log("[Metica] interstitial loaded");
        MeticaAdsCallbacks.Interstitial.OnAdLoadFailed += err => Debug.LogWarning("[Metica] interstitial failed");
        MeticaAdsCallbacks.Interstitial.OnAdShowSuccess += ad => Debug.Log("[Metica] interstitial shown");
        MeticaAdsCallbacks.Interstitial.OnAdHidden += ad => Debug.Log("[Metica] interstitial hidden");
        MeticaAdsCallbacks.Interstitial.OnAdRevenuePaid += ad => Debug.Log("[Metica] interstitial revenue");

INTER_CB
    fi

    if has_format rewarded; then
        cat <<'REWARD_CB'
        MeticaAdsCallbacks.Rewarded.OnAdLoadSuccess += ad => Debug.Log("[Metica] rewarded loaded");
        MeticaAdsCallbacks.Rewarded.OnAdLoadFailed += err => Debug.LogWarning("[Metica] rewarded failed");
        MeticaAdsCallbacks.Rewarded.OnAdShowSuccess += ad => Debug.Log("[Metica] rewarded shown");
        MeticaAdsCallbacks.Rewarded.OnAdHidden += ad => Debug.Log("[Metica] rewarded hidden");
        MeticaAdsCallbacks.Rewarded.OnAdRewarded += ad => Debug.Log("[Metica] rewarded reward granted");
        MeticaAdsCallbacks.Rewarded.OnAdRevenuePaid += ad => Debug.Log("[Metica] rewarded revenue");

REWARD_CB
    fi

    # Privacy + init (privacy must precede init in same file).
    # Uses escaped values; the heredoc still interpolates but the inputs
    # have been sanitized via cs_escape (backslash + quote escaped, control
    # chars rejected up front).
    cat <<INIT
        // Privacy calls must precede Initialize.
        MeticaSdk.Ads.SetHasUserConsent(true);
        MeticaSdk.Ads.SetDoNotSell(false);

        // Initialize the SDK exactly once.
        var config = new MeticaInitConfig("$API_KEY_SAFE", "$APP_ID_SAFE", null);
        MeticaSdk.Initialize(config, null, response => {
            Debug.Log("[Metica] SDK initialized");
        });

INIT

    if has_format banner; then
        cat <<'BANNER_LD'
        MeticaSdk.Ads.CreateBanner("banner_main", new MeticaAdViewConfiguration(MeticaAdViewPosition.BottomCenter));
        MeticaSdk.Ads.LoadBanner("banner_main");
        MeticaSdk.Ads.ShowBanner("banner_main");

BANNER_LD
    fi

    if has_format interstitial; then
        cat <<'INTER_LD'
        MeticaSdk.Ads.LoadInterstitial("interstitial_main");

INTER_LD
    fi

    if has_format rewarded; then
        cat <<'REWARD_LD'
        MeticaSdk.Ads.LoadRewarded("rewarded_main");

REWARD_LD
    fi

    cat <<'METHODS_HEAD'
    }
METHODS_HEAD

    if has_format interstitial; then
        cat <<'INTER_SHOW'

    public void ShowInterstitial()
    {
        if (MeticaSdk.Ads.IsInterstitialReady("interstitial_main"))
            MeticaSdk.Ads.ShowInterstitial("interstitial_main");
    }
INTER_SHOW
    fi

    if has_format rewarded; then
        cat <<'REWARD_SHOW'

    public void ShowRewarded()
    {
        if (MeticaSdk.Ads.IsRewardedReady("rewarded_main"))
            MeticaSdk.Ads.ShowRewarded("rewarded_main");
    }
REWARD_SHOW
    fi

    echo "}"
} > "$OUT_FILE"

echo "Generated: $OUT_FILE (formats: $FORMATS)"
